version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATesTForAZStage2008Project
  gitServerName: kusiAzStage2
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
